display_name: SmartClash

icon: ./assets/images/icon.png

keywords:
  - SmartClash
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: SmartClash

categories:
  - Network

startup_notify: true

include: []
